#!/bin/bash
#PBS -l nodes=4:ppn=4:physical
#PBS -l walltime=00:10:00
#PBS -o /home/Students/cdelaney3/cloud_parallel/Assignment#5_Delaney/job_out16
#PBS -j oe
#PBS -N Assignment#5

date
export PROGRAM="/home/Students/cdelaney3/cloud_parallel/Assignment#5_Delaney/mpihello"
mpirun -machinefile $PBS_NODEFILE $PROGRAM
date
exit 0
