#!/bin/bash
#PBS -l nodes=2:ppn=2:physical
#PBS -l walltime=00:10:00
#PBS -o /home/Students/cdelaney3/cloud_parallel/Assignment#6_Delaney/job_out
#PBS -j oe
#PBS -N matrixMult

date
export PROGRAM="/home/Students/cdelaney3/cloud_parallel/Assignment#6_Delaney/matMult"
mpirun -machinefile $PBS_NODEFILE $PROGRAM 512
date
exit 0
